fos_oauth_server:
    db_driver: orm       # Drivers available: orm, mongodb, or propel
    client_class:        AuthServerBundle\ApiBundle\Entity\Client
    access_token_class:  AuthServerBundle\ApiBundle\Entity\AccessToken
    refresh_token_class: AuthServerBundle\ApiBundle\Entity\RefreshToken
    auth_code_class:     AuthServerBundle\ApiBundle\\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider.username