app_sandbox:
    resource: "@AppSandboxBundle/Controller/"
    type:     annotation
    prefix:   /

oauth2_server:
    resource: "@OAuth2ServerBundle/Controller/"
    type:     annotation
    prefix:   /